        
### ⬆ IMPORTANT PART ⬆ ###

name: Deploy to Render
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Render CLI
        run: |
          curl -o render https://render.com/static/cli/latest/render-linux
          chmod +x render
          sudo mv render /usr/local/bin/render

      - name: Deploy to Render
        run: |
          render login --api-key ${{ secrets.RENDER_API_KEY }}
          render up